// Frontend/Site Internet pour Yolaab/src/app/components/Navigation.tsx
import { Home, Calendar, Users, ShoppingBag, UserCircle } from 'lucide-react';

interface NavigationProps {
  currentPage: string;
  onNavigate: (page: string) => void;
}

export function Navigation({ currentPage, onNavigate }: NavigationProps) {
  const navItems = [
    { id: 'home', icon: Home, label: 'Accueil' },
    { id: 'reservation', icon: Calendar, label: 'Réserver' },
    { id: 'recruitment', icon: Users, label: 'Travailler' },
    { id: 'shop', icon: ShoppingBag, label: 'Boutique' },
  ];

  return (
    <>
      {/* Desktop Navigation */}
      <nav className="hidden md:block bg-blue-600 text-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex items-center justify-between h-20">
            <div 
              className="flex items-center space-x-2 cursor-pointer"
              onClick={() => onNavigate('home')}
            >
              <div className="bg-white text-blue-600 rounded-full p-2">
                <svg className="w-8 h-8" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 2L2 7v10c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V7l-10-5zm0 2.18l8 4v8.82c0 4.2-2.95 8.07-7 9.55V4.18H12z"/>
                </svg>
              </div>
              <span className="text-3xl font-bold">YOLAAB</span>
            </div>
            
            <div className="flex space-x-2">
              {navItems.map((item) => {
                const Icon = item.icon;
                return (
                  <button
                    key={item.id}
                    onClick={() => onNavigate(item.id)}
                    className={`flex flex-col items-center px-6 py-3 rounded-lg transition-all ${
                      currentPage === item.id
                        ? 'bg-white text-blue-600 shadow-lg'
                        : 'hover:bg-blue-500'
                    }`}
                  >
                    <Icon size={28} />
                    <span className="mt-1">{item.label}</span>
                  </button>
                );
              })}
              <button
                onClick={() => onNavigate('admin')}
                className={`flex flex-col items-center px-6 py-3 rounded-lg transition-all ${
                  currentPage === 'admin'
                    ? 'bg-white text-blue-600 shadow-lg'
                    : 'hover:bg-blue-500'
                }`}
              >
                <UserCircle size={28} />
                <span className="mt-1">Admin</span>
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* Mobile Navigation */}
      <div className="md:hidden">
        <div className="bg-blue-600 text-white text-center py-4 shadow-lg">
          <h1 className="text-3xl font-bold">YOLAAB</h1>
          <p className="text-sm mt-1">Keur Massar, Dakar</p>
        </div>
        
        <nav className="fixed bottom-0 left-0 right-0 bg-blue-600 text-white shadow-lg z-50">
          <div className="flex justify-around items-center h-20">
            {navItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.id}
                  onClick={() => onNavigate(item.id)}
                  className={`flex flex-col items-center justify-center flex-1 h-full ${
                    currentPage === item.id
                      ? 'bg-blue-500'
                      : ''
                  }`}
                >
                  <Icon size={28} />
                  <span className="text-xs mt-1">{item.label}</span>
                </button>
              );
            })}
            <button
              onClick={() => onNavigate('admin')}
              className={`flex flex-col items-center justify-center flex-1 h-full ${
                currentPage === 'admin'
                  ? 'bg-blue-500'
                  : ''
              }`}
            >
              <UserCircle size={28} />
              <span className="text-xs mt-1">Admin</span>
            </button>
          </div>
        </nav>
      </div>
    </>
  );
}

// Frontend/components/Navigation.vue
<template>
  <nav class="bg-blue-600 text-white shadow-lg sticky top-0 z-50">
    <!-- Desktop Navigation -->
    <div class="hidden md:block max-w-7xl mx-auto px-4">
      <div class="flex items-center justify-between h-20">
        <NuxtLink
          to="/home"
          class="flex items-center space-x-2 hover:opacity-90 transition"
        >
          <div class="bg-white text-blue-600 rounded-full p-2">
            <span class="text-2xl font-bold">Y</span>
          </div>
          <span class="text-3xl font-bold">YOLAAB</span>
        </NuxtLink>

        <div class="flex space-x-2">
          <NuxtLink
            v-for="item in navItems"
            :key="item.id"
            :to="`/${item.id}`"
            :class="[
              'flex flex-col items-center px-6 py-3 rounded-lg transition-all',
              isActive(item.id)
                ? 'bg-white text-blue-600 shadow-lg'
                : 'hover:bg-blue-500'
            ]"
          >
            <span class="text-2xl">{{ item.emoji }}</span>
            <span class="mt-1 text-sm">{{ item.label }}</span>
          </NuxtLink>
          <NuxtLink
            to="/admin"
            :class="[
              'flex flex-col items-center px-6 py-3 rounded-lg transition-all',
              isActive('admin')
                ? 'bg-white text-blue-600 shadow-lg'
                : 'hover:bg-blue-500'
            ]"
          >
            <span class="text-2xl">🔐</span>
            <span class="mt-1 text-sm">Admin</span>
          </NuxtLink>
        </div>
      </div>
    </div>

    <!-- Mobile Navigation -->
    <div class="md:hidden">
      <div class="text-center py-4">
        <NuxtLink to="/home" class="text-2xl font-bold">YOLAAB</NuxtLink>
        <p class="text-sm mt-1">Keur Massar, Dakar</p>
      </div>
      <nav class="fixed bottom-0 left-0 right-0 bg-blue-600 shadow-lg z-50 border-t border-blue-500">
        <div class="flex justify-around items-center h-20">
          <NuxtLink
            v-for="item in navItems"
            :key="item.id"
            :to="`/${item.id}`"
            class="flex flex-col items-center justify-center flex-1 h-full hover:bg-blue-500 transition"
          >
            <span class="text-2xl">{{ item.emoji }}</span>
            <span class="text-xs mt-1">{{ item.label }}</span>
          </NuxtLink>
          <NuxtLink
            to="/admin"
            class="flex flex-col items-center justify-center flex-1 h-full hover:bg-blue-500 transition"
          >
            <span class="text-2xl">🔐</span>
            <span class="text-xs mt-1">Admin</span>
          </NuxtLink>
        </div>
      </nav>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const navItems = [
  { id: 'home', emoji: '🏠', label: 'Accueil' },
  { id: 'reservation', emoji: '📅', label: 'Réserver' },
  { id: 'recruitment', emoji: '👥', label: 'Travailler' },
  { id: 'shop', emoji: '🛒', label: 'Boutique' },
]

const route = useRoute()

const isActive = (path: string) => {
  return route.path === `/${path}` || (path === 'home' && route.path === '/')
}
</script>
